//
//  TCMyGengoAPIHandlerTests.m
//  mygengoexample
//
//  Created by Christopher Trott on 6/16/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "TCMyGengoAPIHandlerTests.h"

#define SANDBOX_PUBLIC_KEY @"qXXw)^)v$Z(AwLVlYoCE}Wwar57zeI9kCe6G9kREq{2keb~qu0kS9-BuZzAvO=ko"
#define SANDBOX_PRIVATE_KEY @"1D9dM)kk#IGmuvRU3QYZ[~FtbL]dAgnmaw8pea[(u^ns3V-MNRGxgptUf7zyB~LO"

@implementation TCMyGengoAPIHandlerTests

- (id)init{
  if ((self = [super init])){
    [self runTests];
  }
  return self;
}

- (void)runTests{
  TCMyGengoAPICredentials *Credentials = [TCMyGengoAPICredentials sharedCredentials];
  [Credentials setCredentialsWithPublicKey:SANDBOX_PUBLIC_KEY privateKey:SANDBOX_PRIVATE_KEY isSandboxed:YES];
  TCMyGengoAPIHandler *Handler = [[TCMyGengoAPIHandler alloc] initWithDelegate:self];
  
  NIDASSERT([[Credentials publicKey] isEqualToString:SANDBOX_PUBLIC_KEY]);
  NIDASSERT([[Credentials privateKey] isEqualToString:SANDBOX_PRIVATE_KEY]);
  NIDASSERT([Credentials isSandboxed] == YES);
  
  // Testing API Signature function vs. the one generated by Ruby
  NSString *TS = @"1339882478"; //[Handler formattedTimestamp];
  NIDINFO(@"Timestamp: %@", TS);
  NIDINFO(@"API Signature: %@",[Handler apiSignatureWithTimestamp:TS]);
  NIDASSERT([[Handler apiSignatureWithTimestamp:TS] isEqualToString:@"747679f918caa870382a37c9effdd149ff5d1229"]);
  
  // Use this GET call to step through the GET stack.
  [Handler getAccountStats];
  
  [Handler getAccountBalance];
}


- (void)myGengoAPIHandlerDidStartLoad: (TCMyGengoAPIHandler*)handler 
                         fromEndPoint: (NSString*)endpoint{
  NIDINFO(@"%@", endpoint);
  
}

- (void)myGengoAPIHandlerDidLoadDictionary: (TCMyGengoAPIHandler*)handler
                              fromEndPoint: (NSString*)endpoint
                        responseDictionary: (NSDictionary*)response{
  NIDINFO(@"%@ : %@", endpoint, response);
}

- (void)myGengoAPIHandlerDidFail: (TCMyGengoAPIHandler*)handler 
                    fromEndPoint: (NSString*)endpoint
                       withError: (NSError*)error{
  NIDINFO(@"%@ : %@", endpoint, error);
}

@end
